pipelines:
  default:
    - step:
        name: SFTP Deploy
        script:
          - pipe: atlassian/sftp-deploy:0.5.7
            variables:
              USER: chetan
              SERVER: '65.0.114.37'
              REMOTE_PATH: '/var/www/html/'
              LOCAL_PATH: '${BITBUCKET_CLONE_DIR}/*' 
              PASSWORD: Apple@3346